django/04_django_auth/crud/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

django/04_django_auth/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('todos/', include('todos.urls')),
]

django/04_django_auth/crud/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

django/04_django_auth/crud/todos/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Todo(models.Model):
    content = models.CharField(max_length=100)
    due_date = models.DateField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 내가 연결하고 싶은 모델 이름, on_delete =
    # settings.AUTH_USER_MODEL : 장고가 들고 있는 유저 모델을 가져오란 뜻
    

django/04_django_auth/crud/todos/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):

    due_date = forms.CharField(
        widget=forms.TextInput(
            attrs={'type': 'date'},
        )
    )

    class Meta:
        model = Todo
        fields = ('content', 'due_date', ) #다 넣으면 안 되고 하나를 빼야 하는데 그게 user
        

django/04_django_auth/crud/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
# form .forms import ArticleForm 과 같음.
from django.contrib.auth import login as auth_login
# 로그인 가져오기
from django.contrib.auth import logout as auth_logout
# 로그아웃 가져오기

# Create your views here.

def signup(request):
    # user가 가입 했을 때, create를 하는 역할
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = UserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/signup.html', context)

# 구글에서 django github
# python manage.py migrate 해보면 auth.으로 되있는 메세지가 뜸..
# class User는 (AbstaractUser)를 상속받음, 얘는 AbstaractBaseUser상속 받고, 얘는 models.model을 상속받음..
# django usercreationform 검색 2번째 사이트 - 컨트롤 f 유저크리에이션폼 검색
# django.contrib.auth.forms


# 위에 장고에서 불러온게 장고 로그인 따라서 함수 이름 겹침
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST) # request, data 필수인자
        if form.is_valid():
            # form.save()가 아닌 이유.
            # 로그인은 인증만 하는 과정이므로...
            # 검증만한다.
            auth_login(request, form.get_user()) # 2번째 인자로 실제 유저 정보.
            # 장고에서 제공하는 로그인
            return redirect('todos:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/login.html', context) # request에 user 정보가 들어가 있음.
    
# 로그인은 사용자 정보를 바탕으로 디비랑 비교하고 세션을 생성하는것
# 로그아웃은 세션을 파기하는 것.


def logout(request):
    auth_logout(request) # request에는 user정보가 담겨있음.
    return redirect('accounts:login')

django/04_django_auth/crud/todos/views.py
from django.shortcuts import render, redirect
from .forms import TodoForm
from .models import Todo
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required
def index(request):
    form = TodoForm()
    # todos = Todo.objects.all()
    context = {
        'form': form,
        # 'todos': todos,
    }
    return render(request, 'todos/index.html', context)


@login_required
def create(request):
    form = TodoForm(request.POST)
    if form.is_valid():
        todo = form.save(commit=False) #누가 작성한 정보인지 주기 위해 저장하지 않고 잠깐 멈춤
        todo.user = request.user
        todo.save()
        return redirect('todos:index')

def delete(request, pk):
    todo = Todo.objects.get(pk=pk)

    todo.delete()
   
    return redirect('todos:index')

django/04_django_auth/crud/crud/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TODO</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="">ToDo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="#">Memo</a>
      <div class="d-flex flex-row-reverse">
      {% if user.is_authenticated %}
        <span class="nav-item nav-link disabled">{{ user.username }}님 환영합니다</span>
        <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
      {% else %}
        <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
        <a class="nav-item nav-link" href="{% url 'accounts:login' %}">로그인</a>
      {% endif %}
      </div>
    </div>
  </div>
</nav>
  {% block body %}
  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

django/04_django_auth/crud/todos/templates/todos/index.html
{% extends 'base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-6">
            <form action="{% url 'todos:create' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <button>저장</button>
            </form>
            </div>
            <div class="col-6">
            {% for todo in user.todo_set.all %}
                <div class="row">
                <div class="col-sm">
                <h5>{{ todo.content }}</h5>
                <h5>{{ todo.due_date }}</h5>
                </div>
                <div class="col-sm d-flex justify-content-end">
                    <div class="d-flex align-items-center">
                        <form action="{% url 'todos:delete' todo.pk %}" method="POST">
                            {% csrf_token %}
                            <button>삭제</button>
                        </form>
                    </div>
                </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}