django/06_insta/insta/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    #url은 정해진 규칙이 없음 
]

django/06_insta/insta/insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/06_insta/insta/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/like/', views.like, name='like'),
]

django/06_insta/insta/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit, ResizeToFill, ResizeCanvas

# Create your models here.
class User(AbstractUser):
    follow = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='follower')
    # user_set => follower
    image = ProcessedImageField(
                                processors=[ResizeToFill(500, 500)],
                                format='JPEG',
                                options={'quality': 60},
                                default='default.png',
                                )

django/06_insta/insta/posts/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class Post(models.Model):
    content = models.CharField(max_length=200)
    #작성한 사람을 저장
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    #image = models.ImageField()
    image = ProcessedImageField(upload_to='media',
                                processors=[ResizeToFill(500, 500)],
                                format='JPEG',
                                options={'quality': 60})
    #좋아요 버튼을 누른 사람들 저장
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    class Meta:
        ordering = ['-id']

'''
class user
    # post_set = FK -> 어떤 유저가 작성한 글들 
    # like_posts(이전에는 post_set) = M2M -> 어떤 유저가 조항요 버튼 누른 글들
    ==> related_name='like_posts'로 설정을 해줌으로써
    ===> post_set 에서 like_posts로 변수 명이 덮어 씌워짐
'''

django/06_insta/insta/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django.contrib.auth import get_user_model
# get_user_model => AUTH_USER_MODEL에 적용시킨 모델 클래스

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        # 연결하고 싶은 모델이 들어간다
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'image', )

django/06_insta/insta/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('user', 'like_users',)

django/06_insta/insta/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm
from .models import User

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('posts:index')
        
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('posts:index')

    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/form.html', context)


def logout(request):
    auth_logout(request)
    return redirect('accounts:login')


def profile(request, username):
    User = get_user_model()
    #User.objects.get(username=username)
    user_profile = get_object_or_404(get_user_model(), username=username)

    context = {
        'user_profile': user_profile,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def follow(request, user_pk):
    me = request.user
    you = get_object_or_404(get_user_model(), pk=user_pk)

    if me == you:
        return redirect('posts:index')

    # if me in you.follower.all():
    if you in me.follow.all():
        # 이미 팔로우하고 있었음
        # you.follower.remove(me)
        me.follow.remove(you)
    else:
        # 아직 팔로우 안 함
        # you.follower.add(me)
        me.follow.add(you)
    return redirect('accounts:profile', you.username)

django/06_insta/insta/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .forms import PostForm
from .models import Post


# Create your views here.
def index(request):
    posts = Post.objects.all()
    context = {
        'posts':posts,
    }
    return render(request, 'posts/index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')
    else:
        form = PostForm()
    context = {
        'form': form,
    }
    return render(request, 'posts/form.html', context)


@login_required
def like(request, post_pk):
    user = request.user
    post = get_object_or_404(Post, pk=post_pk)

    # user.like_posts = > user가 좋아요 버튼을 누른 게시물들
    # post.like_users => post에 좋아요 버튼을 누른 유저들

    if post in user.like_posts.all():
        #이미 누른 경우
        user.like_posts.remove(post)
        liked = False
    else:
        #아직 안 누른 경우
        user.like_posts.add(post)
        liked = True
    #return redirect('posts:index')
    print("like 함수")
    likedalls = post.like_users.all()
    li = []
    for likedall in likedalls:
        li.append(likedall.username)
    print(li)
    context = {
        'msg': '게시글을 좋아합니다.',
        'liked': liked,
        'li':li,
      
    }

    return JsonResponse(context)

django/06_insta/insta/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
    
    <div class="jumbotron">
        <div class="row">
            <div class="col-4">
                <div class="row">
                    <img class="col-12 rounded-circle" src="{{ user_profile.image.url }}" alt="">
                </div>
            </div>
            <div class="col-8"> 
                <h5>{{ user_profile.username }}</h5>
                <p>팔로우 {{ user_profile.follow.count }}명 팔로워 {{ user_profile.follower.count }}명</p>
                {% if user != user_profile %}
                    {% if user_profile in user.follow.all %}
                        <a class="btn btn-primary" href="{% url 'accounts:follow' user_profile.id %}">팔로우취소</a>
                    {% else %}
                        <a class="btn btn-primary" href="{% url 'accounts:follow' user_profile.id %}">팔로우</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    
    </div>

    <hr>
    <div class="row row-cols-3">
    {% for post in user_profile.post_set.all %}
        
        <div class="col">
            <div class="card">
                 <img src="{{ post.image.url }}" alt="" height="300">
            </div>
        </div>
    {% endfor %}
    </div>

    {% comment %} <h1>profile {{ user_profile.username }}</h1> {% endcomment %}

    {% comment %} {% if user_profile in user.follow.all %}
        <a href="{% url 'accounts:follow' user_profile.id %}">팔로우 취소</a>
    {% else %}
        <a href="{% url 'accounts:follow' user_profile.id %}">팔로우 하기</a>
    {% endif %} {% endcomment %}
{% endblock %}

django/06_insta/insta/insta/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/83da362135.js" crossorigin="anonymous"></script>
</head>
<body>
  {% include 'nav.html' %}
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

django/06_insta/insta/insta/templates/nav.html
<nav class="nav d-flex justify-content-center my-4">
  {% if user.is_authenticated %}
    <a class="nav-link" href="{% url 'posts:index' %}">피드</a>
    <a class="nav-link" href="{% url 'posts:create' %}">글쓰기</a>
    <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
    <a class="nav-link" href="{% url 'accounts:profile' user.username %}">{{ user.username }}</a>
  {% else %}
    <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
    <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
  {% endif %}
</nav>