django/00_django_intro/firstapp/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name="index"), #articles/
    path('dinner/', views.dinner, name='dinner'),
    path('image/', views.image, name='image'),
    path('hello/<str:name>/', views.hello, name='hello'),
    # str 타입 명시는 생략 가능
    # path('hello/<name>/', views.hello),
    path('introduce/<name>/<int:age>/', views.introduce, name='introduce'),
    path('times/<int:num1>/<int:num2>/', views.times, name='times'),
    path('dtl-practice/', views.dtl_practice, name='dtl_practice'),
    path('ispal/<word>/', views.ispal, name='ispal'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('lotto-throw/', views.lotto_throw, name='lotto_throw'),
    path('lotto-catch/', views.lotto_catch, name='lotto_catch'),
    path('artii/', views.artii, name='artii'),
    path('artii-result/', views.artii_result, name='artii_result'),
]

django/00_django_intro/firstapp/firstapp/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views
from pages import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
    # path('pages/', include('pages.urls')),
]

django/00_django_intro/firstapp/pages/urls.py
from django.urls import path
from . import views


app_name = 'pages'
urlpatterns = [

    path('', views.index, name='index'), #pages/

]

django/00_django_intro/firstapp/articles/views.py
# django import style guide
# 1. standard library
# 2. 3rd party library
# 3. django
# 4. local django
 
import random
import requests
from pprint import pprint
from datetime import datetime
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'articles/index.html')


def dinner(request):
    foods = ['족발', '햄버거', '치킨', '초밥']
    pick = random.choice(foods)
    context = {
        'pick': pick,
    }
    return render(request, 'articles/dinner.html', context)


def image(request):
    image_url = 'https://picsum.photos/200/300.jpg'
    context = {
        'image_url': image_url,
    }
    return render(request, 'articles/image.html', context)


def hello(request, name):
    context = {
        'name': name,
    }
    return render(request, 'articles/hello.html', context)


def introduce(request, name, age):
    context = {
        'name': name,
        'age': age,
    }
    return render(request, 'articles/introduce.html', context)


def times(request, num1, num2):
    result = num1 * num2
    context = {
        'num1': num1,
        'num2': num2,
        'result': result,
    }
    return render(request, 'articles/times.html', context)


def dtl_practice(request):
    foods = ['짜장면', '초밥', '차돌짬뽕', '콩국수']
    empty_list = []
    messages = 'Life is short, You need Python'
    datetime_now = datetime.now()
    context = {
        'foods': foods,
        'empty_list': empty_list,
        'messages': messages,
        'datetime_now': datetime_now,
    }
    return render(request, 'articles/dtl_practice.html', context)


def ispal(request, word):
    if word == word[::-1]:
        result = True
    else:
        result = False
    context = {
        'result': result,
        'word' : word,
    }
    return render(request, 'articles/ispal.html', context)


def throw(request):
    return render(request, 'articles/throw.html')


def catch(request):
    # pprint(request.GET)
    # print(request.GET.get('message'))
    msg_list = ['안녕', '방가방가', '전쪽']
    message = request.GET.get('articles/message')
    context = {
        'message': message,
        'msg_list': msg_list,
    }
    return render(request, 'articles/catch.html', context)


def lotto_throw(request):
    return render(request, 'articles/lotto_throw.html')


def lotto_catch(request):
    name = request.GET.get('name')
    numbers = range(1, 46)
    pick = sorted(random.sample(numbers, 6))
    context = {
        'name': name,
        'pick': pick,
    }
    return render(request, 'articles/lotto_catch.html', context)


def artii(request):
    response = requests.get('http://artii.herokuapp.com/fonts_list').text
    fonts_list = response.split('\n')
    context = {
        'fonts_list': fonts_list,
    }
    return render(request, 'articles/artii.html', context)


def artii_result(request):
    # 1. form에서 넘어온 데이터를 받는다.
    word = request.GET.get('word')
    font = request.GET.get('font')

    # 2. ARTII api fontlist로 요청을 보내 폰트 정보를 받는다.
    # response = requests.get('http://artii.herokuapp.com/fonts_list').text
    # print(type(response)) : str
    
    # 3. 문자열 데이터를 리스트로 변환한다.
    # fonts_list = response.split('\n')
    # print(fonts_list)

    # 4. fonts_list에서 폰트 하나 선택
    # font = random.choice(fonts_list)
    
    ARTII_URL = f'http://artii.herokuapp.com/make?text={word}&font={font}'

    # 5. Artii api 주소로 우리가 만든 데이터와 함께 요청을 보낸다.
    result = requests.get(ARTII_URL).text

    context = {
        'result': result,
    }
    return render(request, 'articles/artii_result.html', context)

django/00_django_intro/firstapp/pages/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'pages/index.html')

django/00_django_intro/firstapp/articles/templates/articles/artii.html
{% extends 'base.html' %}


{% block title %} ARTII TITLE {% endblock %}

{% block content %}
  <h1>나만의 ASCII ARTII</h1>
  <form action="{% url 'articles:artii_result' %}" method="GET">
    단어를 입력해주세요 : <input type="text" name="word"><br>
    폰트를 정해주세요 : 
   <select name="font">
     {% for font in fonts_list %}
       <option value="{{ font }}">{{ font }}</option>
     {% endfor %}
    </select>
    <input type="submit" value="만들기!">
    <a href="{% url 'articles:index' %}">인덱스로 가기</a>
  </form>
{% endblock  %}

django/00_django_intro/firstapp/articles/templates/articles/catch.html
{% extends 'base.html' %}


  {% block content %}
    <h1>여기는 catch입니다.</h1>
    <h2>제가 받은 데이터는 {{ message }} 입니다.</h2>
   {% for msg in msg_list%}
     <h2>{{ msg }}</h2>
   {% endfor %}
  {% endblock %}

django/00_django_intro/firstapp/articles/templates/articles/dinner.html
{% extends 'base.html' %}



  {% block content %}
    <h1>오늘의 저녁 메뉴</h1>
    <h2>{{ pick }} 입니다.</h2>
  {% endblock %}

django/00_django_intro/firstapp/articles/templates/articles/dtl_practice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body {
            height: 10000px;
        }
    </style>
</head>
<body>
    <h3>1. 반복문</h3>
    
    {% for food in foods %}
        <p>{{ food }}</p>
    {% endfor %}

    {% for food in foods %}
        <p>{{ forloop.counter }} {{ food }}</p>
    {% endfor %}

    {% for element in empty_list %}
        <p>{{ element }}</p>
    {% empty %}
        <p>지금 아무것도 없네요..</p>
    {% endfor %}
    <hr>

    <h3>2. 조건문</h3>
    {% if '짜장면' in foods %}
        <p>짜장면 역시 또자강!!</p>
    {% endif %}
    <hr>

    {% for food in foods %}
        {% if forloop.first %}
            <p>짜장면엔 고추가루지!!</p>
        {% else %}
            <p>{{ food }}</p>
        {% endif %}
    {% endfor %}
    <hr>

    <h3>3. length filter</h3>
    {% for food in foods %}
        {% if food|length > 2 %}
            <p>메뉴 이름이 너무 길어요</p>
        {% else %}
            <p>{{ food }}, {{ food|length }}</p>
        {% endif %}
    {% endfor %}
    <hr>

    <h3>4. lorem ipsum</h3>
    <p>{% lorem %}</p>
    <hr>
    {% lorem 3 w %}
    <hr>
    {% lorem 4 w random %}
    <hr>

    <h3>5. 글자수 제한</h3>
    <p>{{ messages|truncatewords:3 }}</p>
    <p>{{ messages|truncatechars:3 }}</p>
    <p>{{ messages|truncatechars:10 }}</p>
    <hr>

    <h3>6. 글자 관련 필터</h3>
    <p>{{ 'ABC'|lower }}</p>
    <p>{{ messages|title }}</p>
    <p>{{ 'abc edf'|capfirst }}</p>
    <p>{{ foods|random }}</p>

    <h3>7. 연산</h3>
    <p>{{ 4|add:6 }}</p>

    <h3>8. 날짜 표현</h3>
    <p>{{ datetime_now }}</p>
    <p>{% now "DATETIME_FORMAT" %}</p>
    <p>{% now "DATE_FORMAT" %}</p>
    <p>{% now "SHORT_DATETIME_FORMAT" %}</p>
    <p>{% now "SHORT_DATE_FORMAT" %}</p>

</body>
</html>

django/00_django_intro/firstapp/articles/templates/articles/hello.html
{% extends 'base.html' %}

{% block content %}
    <h1>안녕 {{ name }} !!!</h1>
{% endblock %}

django/00_django_intro/firstapp/articles/templates/articles/image.html
{% extends 'base.html' %}



    {% block content %}
        <h1>랜덤 이미지 출력기</h1>
        <img src="{{ image_url }}" alt="random-img">
    {% endblock %}

django/00_django_intro/firstapp/articles/templates/articles/index.html
{% extends 'base.html' %}



    {% block content %}
        <h1>만나서 반갑습니다!</h1>
    {% endblock %}

django/00_django_intro/firstapp/articles/templates/articles/introduce.html
{% extends 'base.html' %}



    {% block content %}
        <h1>내 이름은 {{ name }}이고 {{ age }}살 입니다.</h1>
    {% endblock %}

django/00_django_intro/firstapp/articles/templates/articles/lotto_catch.html
{% extends 'base.html' %}



  {% block content %}
    <h1>{{ name }}님이 뽑은 번호는 {{ pick }}입니다.</h1>
  {% endblock %}

django/00_django_intro/firstapp/articles/templates/articles/lotto_throw.html
{% extends 'base.html' %}



  {% block content %}
    <form action="{% url 'articles:lotto_catch' %}" method="GET">
      <input type="text" name="name">
      <input type="submit">
    </form>
  {% endblock %}

django/00_django_intro/firstapp/articles/templates/articles/multiplication.html
{% extends 'base.html' %}



    {% block content %}
        <h1>곱셈 결과 : {{result}}</h1>
    {% endblock %}

django/00_django_intro/firstapp/articles/templates/articles/randomimg.html
{% extends 'base.html' %}


    {% block content %}
        <h1>랜덤 이미지 출력</h1>
        <img src="{{URL}}">
    {% endblock %}

django/00_django_intro/firstapp/articles/templates/articles/throw.html
{% extends 'base.html' %}



  {% block content %}
    <h1>Throw</h1>
    <form action="{% url 'articles:catch' %}" method="GET">
      <input type="text" name="message">
     <input type="submit">
    </form>
  {% endblock %}

django/00_django_intro/firstapp/articles/templates/articles/times.html
{% extends 'base.html' %}



    {% block content %}
        <h1>{{ num1 }}와 {{ num2 }}의 곱은 {{ result }} 입니다.</h1>
    {% endblock %}