django/02_django_form/crud/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'), # GET(new) / POST(create)
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'), # GET(edit) / POST(update)
    path('<int:pk>/delete/', views.delete, name='delete')
]

django/02_django_form/crud/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

django/02_django_form/crud/articles/forms.py
from django import forms
from .models import Article


# class ArticleForm(forms.Form):
#     title = forms.CharField(max_length=20)
#     content = forms.CharField(widget=forms.Textarea)


class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        widget=forms.TextInput(
            attrs={
                'class': 'my-title form-control',
                'placeholder': 'Enter the title.',
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'my-content form-control',
                'placeholder': 'Enter the content',
                'cols': 50,
                'rows': 5,
            }
        )
    )

    # Meta - ArticleForm 클래스에 대한 정보를 작성하는 곳
    class Meta:
        model = Article
        # fields = ['title', 'content',]
        fields = '__all__'
        # exclude = ['title'] 

django/02_django_form/crud/articles/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods, require_POST
from .models import Article
from .forms import ArticleForm

# Create your views here.
def index(request):
    articles = Article.objects.all()
    print("----------------------------------------------------------")
   
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


@require_http_methods(['GET', 'POST'])
def create(request):
    # http method POST 일 때
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    # POST가 아닌 다른 methods 일 때
    else: 
        form = ArticleForm()
    context = {
        # form 2가지 모습
        # 1. is_valid()에서 통과하지 못한 form (에러메세지를 포함)
        # 2. else 구문의 form
        'form': form,
    }
    return render(request, 'articles/create.html', context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)


@require_http_methods(['GET', 'POST'])
def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form,
    }
    return render(request, 'articles/update.html', context)


@require_POST
def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index') 

django/02_django_form/crud/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
<h1>NEW</h1>
<form action="{% url 'articles:create' %}" method="POST">
  {% csrf_token %}

  <h3>Version 1</h3>
  {{ form.as_p }}
  
  <hr>

  {% comment %} <h3>Version 2</h3>
  <div>
    {{ form.title.errors }}
    {{ form.title.label_tag }} 
    {{ form.title }}
  </div>
  <div>
    {{ form.content.errors }}
    {{ form.content.label_tag }} 
    {{ form.content }}
  </div>

  <hr>
  {% endcomment %}

  <h3>Version 3</h3>
  {% for field in form %}
    <div class="form-group">
      {{ field.label_tag }}
      {{ field }}
    </div>
  {% endfor %}

  <button class="btn btn-primary">작성</button>
</form>
{% endblock %}

django/02_django_form/crud/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <h2>{{ article.pk }} 번 글</h2>
  <hr>
  <p>제목 : {{ article.title }}</p>
  <p>내용 : {{ article.content }}</p>
  <p>작성 시각 : {{ article.created_at }}</p>
  <p>수정 시각 : {{ article.updated_at }}</p>
  <hr>
  <a href="{% url 'articles:update' article.pk %}">update</a>
  <form action="{% url 'articles:delete' article.pk %}" method='POST'>
    {% csrf_token %}
    <button>delete</button>
  </form>
  <a href="{% url 'articles:index' %}">back</a>
{% endblock %}

django/02_django_form/crud/articles/templates/articles/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}
<h1>UPDATE</h1>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>
{% endblock %}